// Typed source of truth for the global preset seed catalog.
// Used by:
//  - supabase/migrations/019_set_presets_seed.sql  (INSERT source)
//  - FitnessProgramPage beginner surface (static, no DB required)
//  - presetCatalog.test.ts integrity tests
//
// DO NOT add owner_id / id / created_at — those are DB-generated.
// Level 'elite' corresponds to B/I/A "A" (advanced) in the spec voice.

import type { CatalogPreset } from './presetUtils'

export const PRESET_CATALOG: CatalogPreset[] = [
  // ─── Warm-ups ──────────────────────────────────────────────────────────────
  {
    title: 'Easy Start',
    category: 'warmup',
    level: 'beginner',
    stroke: null,
    reps: 4,
    distance: 25,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: [],
    description:
      'First lengths of the session — any stroke, go slow, stand at the wall if you need to. This is a wake-up call, not a test.',
    structure: null,
    family: null,
  },
  {
    title: 'Classic Opener',
    category: 'warmup',
    level: 'intermediate',
    stroke: 'freestyle',
    reps: 1,
    distance: 400,
    rest_type: 'rest_seconds',
    rest_value: 20,
    equipment: ['kickboard'],
    description:
      'The standard club warm-up in miniature: swim to warm the lungs, kick to wake the legs, build 25s to prime your speed. Keep the build-ups controlled — the last 25 should feel fast, not frantic.',
    structure: [
      { reps: 1, distance: 200, note: 'swim' },
      { reps: 1, distance: 100, note: 'kick' },
      { reps: 4, distance: 25, note: 'build' },
    ],
    family: null,
  },
  {
    title: 'Full Club Warm-up',
    category: 'warmup',
    level: 'elite',
    stroke: null,
    reps: 1,
    distance: 600,
    rest_type: 'rest_seconds',
    rest_value: 15,
    equipment: ['kickboard'],
    description:
      'The traditional 700m club opener: swim, kick, drill, then four build 25s. Each block has a job — do not rush through any of them.',
    structure: [
      { reps: 1, distance: 200, note: 'swim' },
      { reps: 1, distance: 200, note: 'kick' },
      { reps: 1, distance: 100, note: 'drill' },
      { reps: 4, distance: 25, note: 'build' },
    ],
    family: null,
  },
  {
    title: 'Wake-up Ladder',
    category: 'warmup',
    level: 'intermediate',
    stroke: 'freestyle',
    reps: 1,
    distance: 300,
    rest_type: 'rest_seconds',
    rest_value: 20,
    equipment: [],
    description:
      'Ascending distances raise heart rate gradually without shock. Start well within yourself — the 150 should feel like stretching out, not racing.',
    structure: [
      { reps: 1, distance: 50 },
      { reps: 1, distance: 100 },
      { reps: 1, distance: 150 },
    ],
    family: null,
  },
  {
    title: 'Mixed Stroke Warm-up',
    category: 'warmup',
    level: 'intermediate',
    stroke: null,
    reps: 6,
    distance: 50,
    rest_type: 'rest_seconds',
    rest_value: 20,
    equipment: [],
    description:
      'Alternating freestyle and backstroke loosens shoulders in both directions. Do not chase the clock — find your rhythm early.',
    structure: null,
    family: null,
  },
  {
    title: 'Beginner Kick Start',
    category: 'warmup',
    level: 'beginner',
    stroke: 'freestyle',
    reps: 4,
    distance: 25,
    rest_type: 'rest_seconds',
    rest_value: 45,
    equipment: ['kickboard'],
    description:
      'Legs-only opener using a kickboard for support. Aim for small, quick kicks from the hips — if you are making big waves, slow down.',
    structure: null,
    family: null,
  },

  // ─── Endurance / aerobic ───────────────────────────────────────────────────
  {
    title: 'First Distance',
    category: 'endurance',
    level: 'beginner',
    stroke: 'freestyle',
    reps: 4,
    distance: 25,
    rest_type: 'rest_seconds',
    rest_value: 40,
    equipment: [],
    description:
      'Steady 25s with time to recover — focus on exhaling fully underwater and turning to breathe rather than lifting your head. The clock does not matter here.',
    structure: null,
    family: null,
  },
  {
    title: 'Building Blocks',
    category: 'endurance',
    level: 'beginner',
    stroke: 'freestyle',
    reps: 6,
    distance: 25,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: [],
    description:
      'Consistency over speed — aim for the same feel on every rep. If the last ones are harder than the first, you went too fast early.',
    structure: null,
    family: null,
  },
  {
    title: 'Steady 50s',
    category: 'endurance',
    level: 'beginner',
    stroke: 'freestyle',
    reps: 4,
    distance: 50,
    rest_type: 'rest_seconds',
    rest_value: 45,
    equipment: [],
    description:
      'First continuous 50m reps — slow is fine. Rest fully, breathe properly, and keep the same stroke count lap to lap.',
    structure: null,
    family: 'aerobic_100s',
  },
  {
    title: 'Aerobic 50s',
    category: 'endurance',
    level: 'intermediate',
    stroke: 'freestyle',
    reps: 8,
    distance: 50,
    rest_type: 'rest_seconds',
    rest_value: 20,
    equipment: [],
    description:
      'Smooth aerobic rhythm across all eight reps, with bilateral breathing every three strokes. You should be able to talk — just not want to.',
    structure: null,
    family: null,
  },
  {
    title: 'The Staple',
    category: 'endurance',
    level: 'intermediate',
    stroke: 'freestyle',
    reps: 10,
    distance: 100,
    rest_type: 'css_offset',
    rest_value: 8,
    equipment: [],
    description:
      'The classic aerobic 100s set that every swimmer eventually comes back to. Even pacing rep to rep matters more than raw speed — count strokes through the set.',
    structure: null,
    family: 'aerobic_100s',
  },
  {
    title: 'Century Club',
    category: 'endurance',
    level: 'elite',
    stroke: 'freestyle',
    reps: 10,
    distance: 100,
    rest_type: 'css_offset',
    rest_value: 5,
    equipment: [],
    description:
      'Tighter turnaround than The Staple — hold your form in the last four reps where it starts to matter. Finish with the same stroke count you started with.',
    structure: null,
    family: 'aerobic_100s',
  },
  {
    title: 'Long Smooth 200s',
    category: 'endurance',
    level: 'intermediate',
    stroke: 'freestyle',
    reps: 4,
    distance: 200,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: [],
    description:
      'Settle into distance rhythm early. Try to negative-split the last one: come home faster than you went out.',
    structure: null,
    family: null,
  },
  {
    title: 'Distance Builder',
    category: 'endurance',
    level: 'elite',
    stroke: 'freestyle',
    reps: 5,
    distance: 200,
    rest_type: 'css_offset',
    rest_value: 6,
    equipment: [],
    description:
      'Aerobic strength set — count strokes each 200 to catch efficiency slipping before your body does. Distance per stroke is everything here.',
    structure: null,
    family: null,
  },
  {
    title: 'The Grinder',
    category: 'endurance',
    level: 'elite',
    stroke: 'freestyle',
    reps: 5,
    distance: 400,
    rest_type: 'rest_seconds',
    rest_value: 45,
    equipment: [],
    description:
      'Long aerobic reps that require mental discipline. The middle 200 of each 400 is where focus is won — keep the pace honest throughout.',
    structure: null,
    family: null,
  },
  {
    title: 'Monument',
    category: 'endurance',
    level: 'elite',
    stroke: 'freestyle',
    reps: 10,
    distance: 400,
    rest_type: 'css_offset',
    rest_value: 8,
    equipment: [],
    description:
      'The big aerobic block, reserved for peak training weeks. Break each 400 in half mentally and execute the second half cleanly.',
    structure: null,
    family: 'aerobic_100s',
  },
  {
    title: 'Continuous Swim',
    category: 'endurance',
    level: 'beginner',
    stroke: null,
    reps: 1,
    distance: 400,
    rest_type: 'none',
    rest_value: null,
    equipment: [],
    description:
      'Time-based endurance for newer swimmers — swim for 15–20 minutes and rest at the wall whenever you need to. Count how many 25s you complete and try to add one next week.',
    structure: null,
    family: null,
  },
  {
    title: 'Descending 100s',
    category: 'endurance',
    level: 'intermediate',
    stroke: 'freestyle',
    reps: 6,
    distance: 100,
    rest_type: 'rest_seconds',
    rest_value: 20,
    equipment: [],
    description:
      'Each rep slightly faster within each group of three — learn your gears. The first 100 should feel comfortable enough that you can genuinely speed up twice.',
    structure: null,
    family: null,
  },

  // ─── Threshold / CSS ───────────────────────────────────────────────────────
  {
    title: 'CSS Intro',
    category: 'threshold',
    level: 'intermediate',
    stroke: 'freestyle',
    reps: 6,
    distance: 100,
    rest_type: 'css_offset',
    rest_value: 4,
    equipment: [],
    description:
      'Just above comfortable aerobic pace — the effort that builds your engine. The send-off time is calculated from your CSS result; trust it.',
    structure: null,
    family: null,
  },
  {
    title: 'CSS 100s',
    category: 'threshold',
    level: 'elite',
    stroke: 'freestyle',
    reps: 10,
    distance: 100,
    rest_type: 'css_offset',
    rest_value: 2,
    equipment: [],
    description:
      'Classic threshold — hit the same split every rep with zero variation. Metronomic pacing is the whole point.',
    structure: null,
    family: null,
  },
  {
    title: 'CSS 200s',
    category: 'threshold',
    level: 'elite',
    stroke: 'freestyle',
    reps: 5,
    distance: 200,
    rest_type: 'css_offset',
    rest_value: 3,
    equipment: [],
    description:
      'Threshold endurance — lap splits should barely drift across the rep. The effort is controlled, not easy.',
    structure: null,
    family: null,
  },
  {
    title: 'Broken 400',
    category: 'threshold',
    level: 'elite',
    stroke: 'freestyle',
    reps: 4,
    distance: 100,
    rest_type: 'rest_seconds',
    rest_value: 10,
    equipment: [],
    description:
      'Race-distance feel with tiny recoveries between each 100. Add up all four split times — that is your broken-400 benchmark.',
    structure: null,
    family: null,
  },
  {
    title: 'Threshold 50s',
    category: 'threshold',
    level: 'intermediate',
    stroke: 'freestyle',
    reps: 12,
    distance: 50,
    rest_type: 'css_offset',
    rest_value: 2,
    equipment: [],
    description:
      'Short reps at threshold pace — the brevity lets you maintain quality across all twelve. Great for developing feel for CSS without the volume of 100s.',
    structure: null,
    family: null,
  },

  // ─── Sprint / speed ────────────────────────────────────────────────────────
  {
    title: 'First Fast 25s',
    category: 'sprint',
    level: 'beginner',
    stroke: 'freestyle',
    reps: 4,
    distance: 25,
    rest_type: 'rest_seconds',
    rest_value: 60,
    equipment: [],
    description:
      'First taste of speed with full recovery — push the first 15m then ease off. Full rest means quality each time.',
    structure: null,
    family: 'sprint_25s',
  },
  {
    title: 'Speed Play 25s',
    category: 'sprint',
    level: 'intermediate',
    stroke: null,
    reps: 8,
    distance: 25,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: [],
    description:
      'Alternating smooth and fast 25s teaches your body two gears. The contrast is the lesson — do not let the easy ones become sloppy.',
    structure: null,
    family: 'sprint_25s',
  },
  {
    title: 'Flat-out 25s',
    category: 'sprint',
    level: 'elite',
    stroke: null,
    reps: 8,
    distance: 25,
    rest_type: 'rest_seconds',
    rest_value: 60,
    equipment: [],
    description:
      'True sprinting needs true rest — full 60 seconds between each. Eight reps of genuine maximum effort.',
    structure: null,
    family: 'sprint_25s',
  },
  {
    title: 'Sprint 50s',
    category: 'sprint',
    level: 'elite',
    stroke: 'freestyle',
    reps: 6,
    distance: 50,
    rest_type: 'rest_seconds',
    rest_value: 90,
    equipment: [],
    description:
      'Push or dive start; log these split times — PB territory. Ninety seconds of rest is there to protect the quality.',
    structure: null,
    family: null,
  },
  {
    title: 'Build 50s',
    category: 'sprint',
    level: 'intermediate',
    stroke: null,
    reps: 6,
    distance: 50,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: [],
    description:
      'Accelerate within each rep so you finish faster than you started. A rep where you hold even pace is a wasted rep.',
    structure: null,
    family: null,
  },
  {
    title: '30×50 Mixer',
    category: 'sprint',
    level: 'elite',
    stroke: null,
    reps: 30,
    distance: 50,
    rest_type: 'interval_seconds',
    rest_value: 90,
    equipment: ['kickboard'],
    description:
      'The Quick/Bowman rotation set — ten cycles of sprint, drill, and kick, each on the same send-off. Kickboard stays on deck between kick reps.',
    structure: null,
    family: null,
  },

  // ─── Kick ──────────────────────────────────────────────────────────────────
  {
    title: 'Kickboard Lengths',
    category: 'kick',
    level: 'beginner',
    stroke: 'freestyle',
    reps: 4,
    distance: 25,
    rest_type: 'rest_seconds',
    rest_value: 45,
    equipment: ['kickboard'],
    description:
      'Small, quick kicks from the hips with the board straight out front. If the board is porpoising, your kicks are too large.',
    structure: null,
    family: 'kick_core',
  },
  {
    title: 'Kick 50s',
    category: 'kick',
    level: 'intermediate',
    stroke: 'freestyle',
    reps: 6,
    distance: 50,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: ['kickboard'],
    description:
      'Steady leg conditioning — resist the urge to use your hands for balance. Hold the same effort every rep.',
    structure: null,
    family: 'kick_core',
  },
  {
    title: 'Kick Ladder',
    category: 'kick',
    level: 'elite',
    stroke: null,
    reps: 1,
    distance: 600,
    rest_type: 'rest_seconds',
    rest_value: 20,
    equipment: ['kickboard'],
    description:
      'Legs create lactate fast — this ladder finds your limits and builds past them. Rest the prescribed time between blocks.',
    structure: [
      { reps: 4, distance: 50 },
      { reps: 2, distance: 100 },
      { reps: 1, distance: 200 },
    ],
    family: 'kick_core',
  },
  {
    title: 'Streamline Kick',
    category: 'kick',
    level: 'intermediate',
    stroke: null,
    reps: 8,
    distance: 25,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: [],
    description:
      'On your back in tight streamline — no board, eyes to the ceiling, small kicks. This is harder than it looks; keep your core engaged.',
    structure: null,
    family: null,
  },
  {
    title: 'Vertical Kick + Swim',
    category: 'kick',
    level: 'elite',
    stroke: 'freestyle',
    reps: 6,
    distance: 50,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: [],
    description:
      'Thirty seconds of eggbeater or scissor kick in deep water, then immediately push into a 50. The legs-to-stroke transition is the work.',
    structure: null,
    family: null,
  },

  // ─── Pull ──────────────────────────────────────────────────────────────────
  {
    title: 'First Pull',
    category: 'pull',
    level: 'beginner',
    stroke: 'freestyle',
    reps: 4,
    distance: 50,
    rest_type: 'rest_seconds',
    rest_value: 60,
    equipment: ['pull buoy'],
    description:
      'Arms-only with the buoy between your legs — finish each stroke past your hips before starting the next. You will feel the difference immediately.',
    structure: null,
    family: 'pull_core',
  },
  {
    title: 'Pull 100s',
    category: 'pull',
    level: 'intermediate',
    stroke: 'freestyle',
    reps: 5,
    distance: 100,
    rest_type: 'rest_seconds',
    rest_value: 25,
    equipment: ['pull buoy'],
    description:
      'Upper-body endurance set — count strokes per 100 and try not to let it rise. Long, efficient strokes beat many short ones.',
    structure: null,
    family: 'pull_core',
  },
  {
    title: 'Pull with Paddles',
    category: 'pull',
    level: 'elite',
    stroke: 'freestyle',
    reps: 4,
    distance: 150,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: ['pull buoy', 'paddles'],
    description:
      'Strength work through added surface area — keep your elbow high on the catch or the paddles punish you. No dragging.',
    structure: null,
    family: 'pull_core',
  },
  {
    title: 'Pull/Kick Alternator',
    category: 'pull',
    level: 'intermediate',
    stroke: 'freestyle',
    reps: 6,
    distance: 50,
    rest_type: 'rest_seconds',
    rest_value: 45,
    equipment: ['pull buoy', 'kickboard'],
    description:
      'Alternating pull and kick reps builds balanced conditioning. Match the effort on both — do not treat kick laps as recovery.',
    structure: null,
    family: null,
  },

  // ─── Technique ─────────────────────────────────────────────────────────────
  {
    title: 'Drill + Swim 50s',
    category: 'technique',
    level: 'beginner',
    stroke: null,
    reps: 6,
    distance: 50,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: [],
    description:
      'Twenty-five metres of drill, then immediately 25m of full stroke — carry the drill feeling into the swim or the second 25 is wasted.',
    structure: null,
    family: null,
  },
  {
    title: 'Catch-up 25s',
    category: 'technique',
    level: 'beginner',
    stroke: 'freestyle',
    reps: 6,
    distance: 25,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: [],
    description:
      'Catch-up drill: one hand waits at full extension until the other arrives. Slows the stroke and builds extension — feel the long position.',
    structure: null,
    family: null,
  },
  {
    title: 'Fist to Fingers',
    category: 'technique',
    level: 'intermediate',
    stroke: 'freestyle',
    reps: 8,
    distance: 50,
    rest_type: 'rest_seconds',
    rest_value: 20,
    equipment: [],
    description:
      'Swim with closed fists to kill grip, then open and feel your forearm catch. The open-hand 25 should feel like you are wearing paddles.',
    structure: null,
    family: null,
  },
  {
    title: 'Stroke Count Challenge',
    category: 'technique',
    level: 'intermediate',
    stroke: 'freestyle',
    reps: 8,
    distance: 25,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: [],
    description:
      'Count strokes every 25 and try to reduce by one rep over rep. Fewer strokes at the same speed means you have improved efficiency.',
    structure: null,
    family: null,
  },
  {
    title: '6-3-6 Set',
    category: 'technique',
    level: 'intermediate',
    stroke: 'freestyle',
    reps: 6,
    distance: 50,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: [],
    description:
      'Six kicks on your side, three strokes, six kicks on the other — rotation and balance drill. Keep your head still.',
    structure: null,
    family: null,
  },
  {
    title: 'Breathing Pattern 200',
    category: 'technique',
    level: 'elite',
    stroke: 'freestyle',
    reps: 1,
    distance: 200,
    rest_type: 'none',
    rest_value: null,
    equipment: [],
    description:
      'Control the breathing cycle: every six strokes, then five, four, three. This is controlled air management, not oxygen deprivation — back off if dizzy.',
    structure: [
      { reps: 1, distance: 50, note: 'breathe every 6 strokes' },
      { reps: 1, distance: 50, note: 'breathe every 5 strokes' },
      { reps: 1, distance: 50, note: 'breathe every 4 strokes' },
      { reps: 1, distance: 50, note: 'breathe every 3 strokes' },
    ],
    family: null,
  },

  // ─── Medley ────────────────────────────────────────────────────────────────
  {
    title: 'IM Intro 25s',
    category: 'medley',
    level: 'intermediate',
    stroke: 'IM',
    reps: 4,
    distance: 25,
    rest_type: 'rest_seconds',
    rest_value: 45,
    equipment: [],
    description:
      'One lap per stroke in butterfly–backstroke–breaststroke–freestyle order. Butterfly can be a drill — learn the sequence before the turns.',
    structure: null,
    family: null,
  },
  {
    title: 'IM 100s',
    category: 'medley',
    level: 'elite',
    stroke: 'IM',
    reps: 4,
    distance: 100,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: [],
    description:
      'Transitions between strokes are the skill — attack the turns and get your feet on the wall before you think about the next stroke. Hold form.',
    structure: null,
    family: null,
  },
  {
    title: 'IM Ladder',
    category: 'medley',
    level: 'elite',
    stroke: 'IM',
    reps: 1,
    distance: 400,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: [],
    description:
      '100 to build confidence, 200 to test fitness, 100 to finish strong. Speed the descent.',
    structure: [
      { reps: 1, distance: 100, note: 'IM' },
      { reps: 1, distance: 200, note: 'IM' },
      { reps: 1, distance: 100, note: 'IM' },
    ],
    family: null,
  },
  {
    title: 'Stroke Rotation 50s',
    category: 'medley',
    level: 'intermediate',
    stroke: null,
    reps: 8,
    distance: 50,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: [],
    description:
      'Rotate through all four strokes across the eight reps. No stroke counts as rest — maintain quality on every lap.',
    structure: null,
    family: null,
  },

  // ─── Pyramids & ladders ────────────────────────────────────────────────────
  {
    title: 'Mini Pyramid',
    category: 'pyramid',
    level: 'beginner',
    stroke: 'freestyle',
    reps: 1,
    distance: 100,
    rest_type: 'rest_seconds',
    rest_value: 40,
    equipment: [],
    description:
      'First pyramid — rest fully between legs. The ascent and descent teach you that the same distance feels different mid-set.',
    structure: [
      { reps: 1, distance: 25 },
      { reps: 1, distance: 50 },
      { reps: 1, distance: 25 },
    ],
    family: 'pyramid',
  },
  {
    title: 'Classic Pyramid',
    category: 'pyramid',
    level: 'intermediate',
    stroke: 'freestyle',
    reps: 1,
    distance: 400,
    rest_type: 'rest_seconds',
    rest_value: 15,
    equipment: [],
    description:
      'The timeless ladder — build to 100 and come back down. The descending side should be faster than the ascending side.',
    structure: [
      { reps: 1, distance: 25 },
      { reps: 1, distance: 50 },
      { reps: 1, distance: 75 },
      { reps: 1, distance: 100 },
      { reps: 1, distance: 75 },
      { reps: 1, distance: 50 },
      { reps: 1, distance: 25 },
    ],
    family: 'pyramid',
  },
  {
    title: 'Big Pyramid',
    category: 'pyramid',
    level: 'elite',
    stroke: 'freestyle',
    reps: 1,
    distance: 1600,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: [],
    description:
      'Up strong, down stronger. Pace the ascent conservatively so you have something left for the 300 and 200 on the way home.',
    structure: [
      { reps: 1, distance: 100 },
      { reps: 1, distance: 200 },
      { reps: 1, distance: 300 },
      { reps: 1, distance: 400 },
      { reps: 1, distance: 300 },
      { reps: 1, distance: 200 },
      { reps: 1, distance: 100 },
    ],
    family: 'pyramid',
  },
  {
    title: 'Troy Descender',
    category: 'pyramid',
    level: 'elite',
    stroke: 'freestyle',
    reps: 1,
    distance: 1500,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: ['pull buoy', 'kickboard'],
    description:
      'Gregg Troy-style descending distance set with rotating modes — swim, pull, kick, drill, build. Each block forces a different kind of effort.',
    structure: [
      { reps: 1, distance: 500, note: 'swim' },
      { reps: 1, distance: 400, note: 'pull' },
      { reps: 1, distance: 300, note: 'kick' },
      { reps: 1, distance: 200, note: 'drill' },
      { reps: 1, distance: 100, note: 'build' },
    ],
    family: null,
  },

  // ─── Race pace ─────────────────────────────────────────────────────────────
  {
    title: 'Race Pace 25s',
    category: 'race_pace',
    level: 'intermediate',
    stroke: null,
    reps: 8,
    distance: 25,
    rest_type: 'interval_seconds',
    rest_value: 60,
    equipment: [],
    description:
      'Hit exact goal race splits — not faster. Rushing the 25s is easy; nailing the exact pace you need is the skill.',
    structure: null,
    family: null,
  },
  {
    title: 'Race Pace 50s',
    category: 'race_pace',
    level: 'elite',
    stroke: null,
    reps: 8,
    distance: 50,
    rest_type: 'rest_seconds',
    rest_value: 60,
    equipment: [],
    description:
      'Back-half training for the 100 — the pace that feels comfortable at the 50m turn must feel controlled here. Log every split.',
    structure: null,
    family: null,
  },
  {
    title: 'Broken 100',
    category: 'race_pace',
    level: 'elite',
    stroke: null,
    reps: 4,
    distance: 25,
    rest_type: 'rest_seconds',
    rest_value: 10,
    equipment: [],
    description:
      'Race simulation with micro-rests — add up your four 25 splits. If the total is close to your 100 PB, you are race ready.',
    structure: null,
    family: null,
  },
  {
    title: 'Goal Pace 100s',
    category: 'race_pace',
    level: 'elite',
    stroke: 'freestyle',
    reps: 5,
    distance: 100,
    rest_type: 'rest_seconds',
    rest_value: 45,
    equipment: [],
    description:
      'Lock in even pacing for your target 400 race pace. No breathing every two on these — three minimum.',
    structure: null,
    family: null,
  },

  // ─── Recovery ──────────────────────────────────────────────────────────────
  {
    title: 'Easy 200',
    category: 'recovery',
    level: 'beginner',
    stroke: null,
    reps: 1,
    distance: 200,
    rest_type: 'none',
    rest_value: null,
    equipment: [],
    description:
      'Flush the arms after a hard set — effort four out of ten, any stroke that unloads what you just trained. Not training; recovery.',
    structure: null,
    family: null,
  },
  {
    title: 'Recovery 50s',
    category: 'recovery',
    level: 'intermediate',
    stroke: null,
    reps: 6,
    distance: 50,
    rest_type: 'rest_seconds',
    rest_value: 20,
    equipment: [],
    description:
      'Recovery is a skill — swim pretty, not fast. Perfect technique at low effort is a training stimulus in itself.',
    structure: null,
    family: null,
  },

  // ─── Cool-downs ────────────────────────────────────────────────────────────
  {
    title: 'Gentle Finish',
    category: 'cooldown',
    level: 'beginner',
    stroke: null,
    reps: 2,
    distance: 25,
    rest_type: 'none',
    rest_value: null,
    equipment: [],
    description:
      'Leave the pool feeling like you won. Two easy lengths to let the session settle.',
    structure: null,
    family: null,
  },
  {
    title: 'Standard Cool-down',
    category: 'cooldown',
    level: 'intermediate',
    stroke: null,
    reps: 1,
    distance: 200,
    rest_type: 'none',
    rest_value: null,
    equipment: [],
    description:
      'Gradually lower the heart rate with long exhales on every stroke. Mix strokes if you want — just keep it easy.',
    structure: null,
    family: null,
  },
  {
    title: 'Full Cool-down',
    category: 'cooldown',
    level: 'elite',
    stroke: null,
    reps: 1,
    distance: 400,
    rest_type: 'rest_seconds',
    rest_value: 15,
    equipment: [],
    description:
      'Shoulders unwind on your back. The backstroke 50s are not rest — they are active recovery.',
    structure: [
      { reps: 1, distance: 200, note: 'easy, any stroke' },
      { reps: 4, distance: 50, note: 'backstroke easy' },
    ],
    family: null,
  },

  // ─── Test sets ─────────────────────────────────────────────────────────────
  {
    title: 'CSS Test',
    category: 'test',
    level: 'intermediate',
    stroke: 'freestyle',
    reps: 1,
    distance: 600,
    rest_type: 'none',
    rest_value: null,
    equipment: [],
    description:
      'Swim an all-out 400m, take 5–10 minutes of easy active recovery, then swim an all-out 200m. Enter both times in the CSS calculator — this session is your training.',
    structure: [
      { reps: 1, distance: 400, note: 'time trial — record your time' },
      { reps: 1, distance: 200, note: 'time trial after 5–10 min active recovery' },
    ],
    family: null,
  },
  {
    title: '7×200 Step Test',
    category: 'test',
    level: 'elite',
    stroke: 'freestyle',
    reps: 7,
    distance: 200,
    rest_type: 'rest_seconds',
    rest_value: 45,
    equipment: [],
    description:
      'Classic step test — log every split across all seven. A smooth step curve shows you are fit; a cliff shows where aerobic capacity ends.',
    structure: null,
    family: null,
  },
  {
    title: 'Timed 30-minute Swim',
    category: 'test',
    level: 'intermediate',
    stroke: 'freestyle',
    reps: 1,
    distance: 1500,
    rest_type: 'none',
    rest_value: null,
    equipment: [],
    description:
      'Swim continuously for exactly 30 minutes and count your total distance. Record it — repeat monthly to measure fitness improvement.',
    structure: null,
    family: null,
  },
  {
    title: '100 Time Trial',
    category: 'test',
    level: 'intermediate',
    stroke: null,
    reps: 1,
    distance: 100,
    rest_type: 'none',
    rest_value: null,
    equipment: [],
    description:
      'All-out from a push start — no pacing, no saving. Log it. This is your benchmark.',
    structure: null,
    family: null,
  },

  // ─── Level-gap fillers (#66–75) ───────────────────────────────────────────
  // Added to fill missing levels within existing families and categories.
  {
    title: 'CSS Starter',
    category: 'threshold',
    level: 'beginner',
    stroke: 'freestyle',
    reps: 4,
    distance: 50,
    rest_type: 'css_offset',
    rest_value: 6,
    equipment: [],
    description:
      'First dip into threshold pace — slightly faster than your usual aerobic effort, but still very controlled. Count your strokes and aim not to let the number rise.',
    structure: null,
    family: null,
  },
  {
    title: 'Aerobic 100s Entry',
    category: 'endurance',
    level: 'beginner',
    stroke: 'freestyle',
    reps: 4,
    distance: 100,
    rest_type: 'rest_seconds',
    rest_value: 60,
    equipment: [],
    description:
      'Your first 100m reps — slow is absolutely fine. The goal is to keep going without stopping; speed comes later.',
    structure: null,
    family: 'aerobic_100s',
  },
  {
    title: 'IM Starter',
    category: 'medley',
    level: 'beginner',
    stroke: 'IM',
    reps: 4,
    distance: 25,
    rest_type: 'rest_seconds',
    rest_value: 60,
    equipment: [],
    description:
      'One lap of each stroke in butterfly–backstroke–breaststroke–freestyle order. Fly can be a drill — learn the sequence before worrying about the turns.',
    structure: null,
    family: null,
  },
  {
    title: 'First Race Pace',
    category: 'race_pace',
    level: 'beginner',
    stroke: 'freestyle',
    reps: 4,
    distance: 25,
    rest_type: 'interval_seconds',
    rest_value: 60,
    equipment: [],
    description:
      'Find what fast feels like with full recovery between each rep. Do not pace it — push, then recover fully.',
    structure: null,
    family: null,
  },
  {
    title: 'Recovery 100s',
    category: 'recovery',
    level: 'elite',
    stroke: null,
    reps: 4,
    distance: 100,
    rest_type: 'none',
    rest_value: null,
    equipment: [],
    description:
      'Post-hard-session flush using whatever stroke unloads your tired muscles most. Effort below five out of ten — this is recovery, not base training.',
    structure: null,
    family: null,
  },
  {
    title: 'Reverse Pyramid',
    category: 'pyramid',
    level: 'elite',
    stroke: 'freestyle',
    reps: 1,
    distance: 1000,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: [],
    description:
      'Descending distances reward honest pacing on the long reps — no saving energy for the 100 at the end. Come home fast.',
    structure: [
      { reps: 1, distance: 400 },
      { reps: 1, distance: 300 },
      { reps: 1, distance: 200 },
      { reps: 1, distance: 100 },
    ],
    family: 'pyramid',
  },
  {
    title: 'Pull Threshold',
    category: 'pull',
    level: 'intermediate',
    stroke: 'freestyle',
    reps: 6,
    distance: 100,
    rest_type: 'css_offset',
    rest_value: 4,
    equipment: ['pull buoy'],
    description:
      'Arms-only threshold set — removes kick fatigue so you can focus on holding send-off pace with the upper body. Count strokes to track efficiency.',
    structure: null,
    family: 'pull_core',
  },
  {
    title: 'Extended Kick',
    category: 'kick',
    level: 'elite',
    stroke: 'freestyle',
    reps: 4,
    distance: 100,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: ['kickboard'],
    description:
      'Race-length kick conditioning — your second half depends on legs that still work at the 300m mark. Hold an even tempo.',
    structure: null,
    family: 'kick_core',
  },
  {
    title: 'Backstroke Basics',
    category: 'technique',
    level: 'beginner',
    stroke: 'backstroke',
    reps: 4,
    distance: 25,
    rest_type: 'rest_seconds',
    rest_value: 30,
    equipment: [],
    description:
      'Pinky-first entry, tall hips, and small quick kicks. Backstroke efficiency comes from core stability, not arm power.',
    structure: null,
    family: null,
  },
  {
    title: 'Rotation Drill Set',
    category: 'technique',
    level: 'elite',
    stroke: null,
    reps: 1,
    distance: 400,
    rest_type: 'rest_seconds',
    rest_value: 20,
    equipment: [],
    description:
      'Four drill 50s to build the movement pattern, then four swim 50s to use it. If the swim 50s do not feel different, go back to the drill.',
    structure: [
      { reps: 4, distance: 50, note: 'rotation drill' },
      { reps: 4, distance: 50, note: 'swim — carry the rotation' },
    ],
    family: null,
  },
]

/** All beginner-level presets — used for the static beginner surface. */
export const BEGINNER_PRESETS: CatalogPreset[] = PRESET_CATALOG.filter(
  (p) => p.level === 'beginner',
)
